server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/security?serverTimezone=Asia/Seoul
    username: security
    password: security1234

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 32866128321-m4df8ar6rfepbdvgeglmqbcpsgqgi1ff.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile